-- ==========================================================
-- SCRIPT DE BANCO DE DADOS - HOSPITAL
-- ==========================================================

-- 1. LIMPEZA DO AMBIENTE (Para evitar erros de tabelas já existentes)
BEGIN
   FOR c IN (SELECT table_name FROM user_tables) LOOP
      EXECUTE IMMEDIATE 'DROP TABLE ' || c.table_name || ' CASCADE CONSTRAINTS';
   END LOOP;
   FOR p IN (SELECT object_name FROM user_objects WHERE object_type = 'PROCEDURE') LOOP
      EXECUTE IMMEDIATE 'DROP PROCEDURE ' || p.object_name;
   END LOOP;
END;
/

-- 2. CRIAÇÃO DAS TABELAS

CREATE TABLE PLANO_SAUDE (
    PLANO_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME_OPERADORA VARCHAR2(100) NOT NULL
);

CREATE TABLE BENEFICIARIO (
    BENEFICIARIO_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME_PACIENTE VARCHAR2(150) NOT NULL,
    DOCUMENTO_CPF VARCHAR2(11) UNIQUE NOT NULL,
    DTA_NASC DATE NOT NULL,
    PLANO_ID NUMBER,
    FOREIGN KEY (PLANO_ID) REFERENCES PLANO_SAUDE(PLANO_ID)
);

CREATE TABLE CORPO_CLINICO (
    PROFISSIONAL_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME_MEDICO VARCHAR2(150) NOT NULL,
    TIPO_PROF VARCHAR2(50) NOT NULL,
    ESPECIALIDADE_DESC VARCHAR2(100)
);

CREATE TABLE UNIDADE_HOSPITALAR (
    UNIDADE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DESCRICAO_UNIDADE VARCHAR2(150) NOT NULL
);

CREATE TABLE ACOMODACAO (
    ACOMODACAO_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    IDENTIFICADOR_LEITO VARCHAR2(10) NOT NULL,
    SITUACAO VARCHAR2(20) NOT NULL,
    UNIDADE_ID NUMBER,
    FOREIGN KEY (UNIDADE_ID) REFERENCES UNIDADE_HOSPITALAR(UNIDADE_ID)
);

CREATE TABLE REGISTRO_ATENDIMENTO (
    REGISTRO_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    BENEFICIARIO_ID NUMBER,
    PROFISSIONAL_ID NUMBER,
    HIPOTESE_DIAGNOSTICA VARCHAR2(200),
    DTA_INICIO_ATEND DATE DEFAULT SYSDATE,
    FOREIGN KEY (BENEFICIARIO_ID) REFERENCES BENEFICIARIO(BENEFICIARIO_ID),
    FOREIGN KEY (PROFISSIONAL_ID) REFERENCES CORPO_CLINICO(PROFISSIONAL_ID)
);

CREATE TABLE ADMISSAO_PACIENTE (
    ADMISSAO_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    REGISTRO_ID NUMBER NOT NULL,
    ACOMODACAO_ID NUMBER NOT NULL,
    DTA_ENTRADA DATE DEFAULT SYSDATE,
    DTA_ALTA_EFETIVA DATE,
    FOREIGN KEY (REGISTRO_ID) REFERENCES REGISTRO_ATENDIMENTO(REGISTRO_ID),
    FOREIGN KEY (ACOMODACAO_ID) REFERENCES ACOMODACAO(ACOMODACAO_ID)
);

CREATE TABLE CATALOGO_SERVICO (
    SERVICO_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DESCRICAO_SERVICO VARCHAR2(200) NOT NULL,
    VALOR_BASE NUMBER(10,2)
);

CREATE TABLE ITENS_ATENDIMENTO (
    ITEM_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    REGISTRO_ID NUMBER NOT NULL,
    SERVICO_ID NUMBER NOT NULL,
    QUANTIDADE NUMBER DEFAULT 1,
    VALOR_REGISTRADO NUMBER(10,2),
    FOREIGN KEY (REGISTRO_ID) REFERENCES REGISTRO_ATENDIMENTO(REGISTRO_ID),
    FOREIGN KEY (SERVICO_ID) REFERENCES CATALOGO_SERVICO(SERVICO_ID)
);

-- CRIAÇÃO DE ÍNDICES
CREATE INDEX IDX_REG_PACIENTE ON REGISTRO_ATENDIMENTO (BENEFICIARIO_ID);
CREATE INDEX IDX_REG_MEDICO ON REGISTRO_ATENDIMENTO (PROFISSIONAL_ID);
CREATE INDEX IDX_LEITO_STATUS ON ACOMODACAO (SITUACAO);

-- 3. AUTOMAÇÃO (TRIGGER E PROCEDURE)

-- Trigger: Atualiza automaticamente se o leito está LIVRE ou OCUPADO
CREATE OR REPLACE TRIGGER TRG_GERENCIA_STATUS_LEITO
AFTER INSERT OR UPDATE OF DTA_ALTA_EFETIVA ON ADMISSAO_PACIENTE
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        UPDATE ACOMODACAO SET SITUACAO = 'OCUPADO' WHERE ACOMODACAO_ID = :NEW.ACOMODACAO_ID;
    ELSIF UPDATING AND :NEW.DTA_ALTA_EFETIVA IS NOT NULL THEN
        UPDATE ACOMODACAO SET SITUACAO = 'LIVRE' WHERE ACOMODACAO_ID = :NEW.ACOMODACAO_ID;
    END IF;
END;
/

-- Procedure: Lança itens na conta buscando o valor correto no catálogo
CREATE OR REPLACE PROCEDURE PRC_LANCAR_ITEM_CONTA (
    p_registro_id IN NUMBER,
    p_servico_id  IN NUMBER
) IS
    v_valor NUMBER(10,2);
BEGIN
    SELECT VALOR_BASE INTO v_valor FROM CATALOGO_SERVICO WHERE SERVICO_ID = p_servico_id;
    
    INSERT INTO ITENS_ATENDIMENTO (REGISTRO_ID, SERVICO_ID, QUANTIDADE, VALOR_REGISTRADO)
    VALUES (p_registro_id, p_servico_id, 1, v_valor);
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Item lançado com sucesso.');
END;
/

-- 4. INSERÇÃO DE DADOS

INSERT INTO PLANO_SAUDE (NOME_OPERADORA) VALUES ('Unimed');
INSERT INTO PLANO_SAUDE (NOME_OPERADORA) VALUES ('Amil');
INSERT INTO PLANO_SAUDE (NOME_OPERADORA) VALUES ('SulAmérica');
INSERT INTO PLANO_SAUDE (NOME_OPERADORA) VALUES ('Particular');

INSERT INTO BENEFICIARIO (NOME_PACIENTE, DOCUMENTO_CPF, DTA_NASC, PLANO_ID)
VALUES ('Arthur Martins', '12345678901', TO_DATE('1990-05-20','YYYY-MM-DD'), 1);
INSERT INTO BENEFICIARIO (NOME_PACIENTE, DOCUMENTO_CPF, DTA_NASC, PLANO_ID)
VALUES ('Maria Souza', '23456789012', TO_DATE('1985-11-12','YYYY-MM-DD'), 2);
INSERT INTO BENEFICIARIO (NOME_PACIENTE, DOCUMENTO_CPF, DTA_NASC, PLANO_ID)
VALUES ('João Pedro', '34567890123', TO_DATE('2000-02-01','YYYY-MM-DD'), 3);
INSERT INTO BENEFICIARIO (NOME_PACIENTE, DOCUMENTO_CPF, DTA_NASC, PLANO_ID)
VALUES ('Ana Lima', '45678901234', TO_DATE('1995-07-18','YYYY-MM-DD'), 4);
INSERT INTO BENEFICIARIO (NOME_PACIENTE, DOCUMENTO_CPF, DTA_NASC, PLANO_ID)
VALUES ('Fernanda Oliveira', '56789012345', TO_DATE('1999-03-10','YYYY-MM-DD'), 1);
INSERT INTO BENEFICIARIO (NOME_PACIENTE, DOCUMENTO_CPF, DTA_NASC, PLANO_ID)
VALUES ('Carlos Alberto', '67890123456', TO_DATE('1979-01-25','YYYY-MM-DD'), 2);
INSERT INTO BENEFICIARIO (NOME_PACIENTE, DOCUMENTO_CPF, DTA_NASC, PLANO_ID)
VALUES ('Gabriel Silva', '78901234567', TO_DATE('2002-12-09','YYYY-MM-DD'), 3);
INSERT INTO BENEFICIARIO (NOME_PACIENTE, DOCUMENTO_CPF, DTA_NASC, PLANO_ID)
VALUES ('Beatriz Fernandes', '89012345678', TO_DATE('1991-08-03','YYYY-MM-DD'), 4);

INSERT INTO CORPO_CLINICO (NOME_MEDICO, TIPO_PROF, ESPECIALIDADE_DESC) VALUES ('Dr. Henrique Almeida', 'Médico', 'Cardiologia');
INSERT INTO CORPO_CLINICO (NOME_MEDICO, TIPO_PROF, ESPECIALIDADE_DESC) VALUES ('Dra. Carolina Torres', 'Médica', 'Pediatria');
INSERT INTO CORPO_CLINICO (NOME_MEDICO, TIPO_PROF, ESPECIALIDADE_DESC) VALUES ('Dr. Rafael Nogueira', 'Médico', 'Clinico Geral');
INSERT INTO CORPO_CLINICO (NOME_MEDICO, TIPO_PROF, ESPECIALIDADE_DESC) VALUES ('Dra. Larissa Mendes', 'Médica', 'Ginecologia');
INSERT INTO CORPO_CLINICO (NOME_MEDICO, TIPO_PROF, ESPECIALIDADE_DESC) VALUES ('Dr. Paulo Santoro', 'Médico', 'Ortopedia');

INSERT INTO UNIDADE_HOSPITALAR (DESCRICAO_UNIDADE) VALUES ('Emergência');
INSERT INTO UNIDADE_HOSPITALAR (DESCRICAO_UNIDADE) VALUES ('Internação');
INSERT INTO UNIDADE_HOSPITALAR (DESCRICAO_UNIDADE) VALUES ('Laboratório');
INSERT INTO UNIDADE_HOSPITALAR (DESCRICAO_UNIDADE) VALUES ('Centro Cirúrgico');

-- Loop para criar os 20 leitos
BEGIN
    FOR i IN 1..20 LOOP
        INSERT INTO ACOMODACAO (IDENTIFICADOR_LEITO, SITUACAO, UNIDADE_ID)
        VALUES ('L'||i, CASE WHEN MOD(i,3)=0 THEN 'OCUPADO' ELSE 'LIVRE' END, CASE WHEN i <= 4 THEN 1 WHEN i <= 8 THEN 2 ELSE 3 END);
    END LOOP;
END;
/

INSERT INTO CATALOGO_SERVICO (DESCRICAO_SERVICO, VALOR_BASE) VALUES ('Consulta clínica', 150);
INSERT INTO CATALOGO_SERVICO (DESCRICAO_SERVICO, VALOR_BASE) VALUES ('Exame de sangue', 40);
INSERT INTO CATALOGO_SERVICO (DESCRICAO_SERVICO, VALOR_BASE) VALUES ('Raio-X', 120);
INSERT INTO CATALOGO_SERVICO (DESCRICAO_SERVICO, VALOR_BASE) VALUES ('Ultrassonografia', 230);
INSERT INTO CATALOGO_SERVICO (DESCRICAO_SERVICO, VALOR_BASE) VALUES ('Tomografia', 680);
INSERT INTO CATALOGO_SERVICO (DESCRICAO_SERVICO, VALOR_BASE) VALUES ('Ressonância magnética', 1450);

INSERT INTO REGISTRO_ATENDIMENTO (BENEFICIARIO_ID, PROFISSIONAL_ID, HIPOTESE_DIAGNOSTICA) VALUES (1, 1, 'Dor no peito');
INSERT INTO REGISTRO_ATENDIMENTO (BENEFICIARIO_ID, PROFISSIONAL_ID, HIPOTESE_DIAGNOSTICA) VALUES (2, 2, 'Febre e tosse');
INSERT INTO REGISTRO_ATENDIMENTO (BENEFICIARIO_ID, PROFISSIONAL_ID, HIPOTESE_DIAGNOSTICA) VALUES (3, 3, 'Dor abdominal');
INSERT INTO REGISTRO_ATENDIMENTO (BENEFICIARIO_ID, PROFISSIONAL_ID, HIPOTESE_DIAGNOSTICA) VALUES (4, 4, 'Acompanhamento ginecológico');

-- Internações (A Trigger vai disparar aqui)
INSERT INTO ADMISSAO_PACIENTE (REGISTRO_ID, ACOMODACAO_ID) VALUES (1, 3);
INSERT INTO ADMISSAO_PACIENTE (REGISTRO_ID, ACOMODACAO_ID) VALUES (2, 6);
INSERT INTO ADMISSAO_PACIENTE (REGISTRO_ID, ACOMODACAO_ID) VALUES (3, 9);

INSERT INTO ITENS_ATENDIMENTO (REGISTRO_ID, SERVICO_ID, QUANTIDADE, VALOR_REGISTRADO) VALUES (1, 1, 1, 150);
INSERT INTO ITENS_ATENDIMENTO (REGISTRO_ID, SERVICO_ID, QUANTIDADE, VALOR_REGISTRADO) VALUES (1, 2, 1, 40);
INSERT INTO ITENS_ATENDIMENTO (REGISTRO_ID, SERVICO_ID, QUANTIDADE, VALOR_REGISTRADO) VALUES (2, 1, 1, 150);
INSERT INTO ITENS_ATENDIMENTO (REGISTRO_ID, SERVICO_ID, QUANTIDADE, VALOR_REGISTRADO) VALUES (2, 3, 1, 120);

-- Salvar tudo
COMMIT;

-- 5. RELATÓRIOS (CONSULTAS)

-- Relatório: Taxa de Ocupação
SELECT
    uh.DESCRICAO_UNIDADE AS SETOR,
    COUNT(ac.ACOMODACAO_ID) AS TOTAL_LEITOS,
    SUM(CASE WHEN ac.SITUACAO = 'OCUPADO' THEN 1 ELSE 0 END) AS LEITOS_OCUPADOS,
    ROUND((SUM(CASE WHEN ac.SITUACAO = 'OCUPADO' THEN 1 ELSE 0 END) * 100) / COUNT(ac.ACOMODACAO_ID), 2) AS TAXA_OCUPACAO
FROM ACOMODACAO ac
JOIN UNIDADE_HOSPITALAR uh ON uh.UNIDADE_ID = ac.UNIDADE_ID
GROUP BY uh.DESCRICAO_UNIDADE
ORDER BY TAXA_OCUPACAO DESC;



-- ÁREA DE APRESENTAÇÃO (NA HORA DE TESTAR)

SET SERVEROUTPUT ON;

-- 1. TESTE DO TRIGGER (O Leito muda sozinho)

-- Verificando que o Leito 20 está LIVRE
SELECT IDENTIFICADOR_LEITO, SITUACAO FROM ACOMODACAO WHERE ACOMODACAO_ID = 20;

-- Internando paciente no Leito 20 (Trigger dispara aqui)
INSERT INTO ADMISSAO_PACIENTE (REGISTRO_ID, ACOMODACAO_ID) VALUES (1, 20);

-- Verificando que virou OCUPADO
SELECT IDENTIFICADOR_LEITO, SITUACAO FROM ACOMODACAO WHERE ACOMODACAO_ID = 20;

-- Dando alta para liberar
UPDATE ADMISSAO_PACIENTE SET DTA_ALTA_EFETIVA = SYSDATE WHERE ACOMODACAO_ID = 20;

-- Verificando que voltou a ficar LIVRE
SELECT IDENTIFICADOR_LEITO, SITUACAO FROM ACOMODACAO WHERE ACOMODACAO_ID = 20;


-- 2. TESTE DA PROCEDURE (Lança conta automático)

-- Lançando uma Tomografia (ID 5) para o paciente 1
BEGIN
    PRC_LANCAR_ITEM_CONTA(p_registro_id => 1, p_servico_id => 5);
END;
/

-- Verificando se gravou o preço (680.00) corretamente
-- SEM USAR SELECT *
SELECT REGISTRO_ID, SERVICO_ID, QUANTIDADE, VALOR_REGISTRADO 
FROM ITENS_ATENDIMENTO 
WHERE SERVICO_ID = 5;